env:
  commonjs: true
  es6: true
  node: true
extends: 'plugin:prettier/recommended'
parserOptions:
  ecmaVersion: 2018
plugins:
  - prettier
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - 0
  prettier/prettier:
    - error
    - singleQuote: true
      
